#!/bin/bash

# Import workbooks
python import_workbooks.py

# clean and classify data into categories
python prep_data.py

# generate stats
python analysis.py


# update the json source and csv files
# and push them to the Github repo
git add *.json
git add *.csv
git commit -m"updated invoice data $(date)"
git push origin master
